### ISSUE TITLE
Decryption in Infinix Zero 8

### ISSUE THREAD

**Issue by HemanthJabalpuri** [lopestom/device_TWRP-PBRP_BLU_G0370WW#1]
@lopestom
Sir, thanks for this TWRP with working decryption.

I am trying to fix decryption in TWRP of Infinix Zero 8. I followed your tree as reference. It is stuck at TWRP logo.

Tree is at https://github.com/HemanthJabalpuri/android_device_infinix_X687/tree/test

Log of stuck on logo:- 
[decryption1.log](https://github.com/lopestom/device_TWRP-PBRP_BLU_G0370WW/files/6788766/decryption1.log)

```
07-08 16:04:19.319   355   355 W ServiceManagement: Waited one second for android.hardware.keymaster@4.0::IKeymasterDevice/default
07-08 16:04:19.320   355   355 I ServiceManagement: getService: Trying again for android.hardware.keymaster@4.0::IKeymasterDevice/default...
```

May be with your suggestions I can go further.

Thanks

**Comment by lopestom** [comment]
You need change files properly from stock like my keymaster of stock keymaster file from your device.
Others informations can same but other can different like partitions size; screen size; etc....

I'll go see your three device but maybe need more info by device. So you know how to do that?

**Comment by HemanthJabalpuri** [comment]
Thanks for replying

I did changed all the stuff that is specific to Infinix Zero 8 in my device tree. But the result is above one.

**Comment by lopestom** [comment]
Okay. Wait my free time or send me invite in hangouts/chat google with my email.

**Comment by HemanthJabalpuri** [comment]
Can't able to find your email anywhere. This is my mail hemanthjabalpuri@gmail.com

Thanks

**Comment by lopestom** [comment]
> Can't able to find your email anywhere. This is my mail [hemanthjabalpuri@gmail.com](mailto:hemanthjabalpuri@gmail.com)
> 
> Thanks

Sent invitation.
